// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SAF.VSIX
{
    static class Vsix
    {
        public const string Id = "5962e87f-5192-4d26-91f3-62efd4012ff5";
        public const string Name = "SAF Extension for Visual Studio";
        public const string Description = @"A Visual Studio Extension that brings SAF features into Visual Studio and highly simplifies the installation and maintenance of Sitecore Experience Platform.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Rosen Petrov";
        public const string Tags = "sitecore, devops, installation";
    }
}
