// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SAF.VSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNewSSLCertificatesCommandPackageString = "50ea28c6-3f76-4641-a15e-de9fa78717cd";
        public const string guidNewSSLCertificatesCommandPackageCmdSetString = "1f5c3fe8-b14a-4f59-a6c4-ddd8c8ec6c99";
        public const string guidImagesString = "5c1a2768-126b-46fd-a410-24a7bb518418";
        public static Guid guidNewSSLCertificatesCommandPackage = new Guid(guidNewSSLCertificatesCommandPackageString);
        public static Guid guidNewSSLCertificatesCommandPackageCmdSet = new Guid(guidNewSSLCertificatesCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SAFMenuGroup = 0x1020;
        public const int NewSSLCertificatesCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
